// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace IndexLessNamespace {
  export interface IIndexLess {
    'ant-advanced-search-form': string;
    'ant-form-item': string;
    'ant-form-item-control-wrapper': string;
    wrapper: string;
  }
}

declare const IndexLessModule: IndexLessNamespace.IIndexLess & {
  /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
  locals: IndexLessNamespace.IIndexLess;
};

export = IndexLessModule;
